export const CATEGORYGROUP_CREATE_REQUEST = 'CATEGORYGROUP_CREATE_REQUEST'
export const CATEGORYGROUP_CREATE_SUCCESS = 'CATEGORYGROUP_CREATE_SUCCESS'
export const CATEGORYGROUP_CREATE_FAILED = 'CATEGORYGROUP_CREATE_FAILED'
export const CATEGORYGROUP_CREATE_RESET = 'CATEGORYGROUP_CREATE_RESET'

export const CATEGORYGROUP_LIST_REQUEST = 'CATEGORYGROUP_LIST_REQUEST'
export const CATEGORYGROUP_LIST_SUCCESS = 'CATEGORYGROUP_LIST_SUCCESS'
export const CATEGORYGROUP_LIST_FAILED = 'CATEGORYGROUP_LIST_FAILED'

export const CATEGORYGROUP_DETAILS_REQUEST = 'CATEGORYGROUP_DETAILS_REQUEST'
export const CATEGORYGROUP_DETAILS_SUCCESS = 'CATEGORYGROUP_DETAILS_SUCCESS'
export const CATEGORYGROUP_DETAILS_FAILED = 'CATEGORYGROUP_DETAILS_FAILED'

export const CATEGORYGROUP_UPDATE_REQUEST = 'CATEGORYGROUP_UPDATE_REQUEST'
export const CATEGORYGROUP_UPDATE_SUCCESS = 'CATEGORYGROUP_UPDATE_SUCCESS'
export const CATEGORYGROUP_UPDATE_FAILED = 'CATEGORYGROUP_UPDATE_FAILED'
export const CATEGORYGROUP_UPDATE_RESET = 'CATEGORYGROUP_UPDATE_RESET'

export const CATEGORYGROUP_DELETE_REQUEST = 'CATEGORYGROUP_DELETE_REQUEST'
export const CATEGORYGROUP_DELETE_SUCCESS = 'CATEGORYGROUP_DELETE_SUCCESS'
export const CATEGORYGROUP_DELETE_FAILED = 'CATEGORYGROUP_DELETE_FAILED'
