export const TABLE_CREATE_REQUEST = 'TABLE_CREATE_REQUEST'
export const TABLE_CREATE_SUCCESS = 'TABLE_CREATE_SUCCESS'
export const TABLE_CREATE_FAILED = 'TABLE_CREATE_FAILED'
export const TABLE_CREATE_RESET = 'TABLE_CREATE_RESET'

export const TABLE_LIST_REQUEST = 'TABLE_LIST_REQUEST'
export const TABLE_LIST_SUCCESS = 'TABLE_LIST_SUCCESS'
export const TABLE_LIST_FAILED = 'TABLE_LIST_FAILED'

export const TABLE_DETAILS_REQUEST = 'TABLE_DETAILS_REQUEST'
export const TABLE_DETAILS_SUCCESS = 'TABLE_DETAILS_SUCCESS'
export const TABLE_DETAILS_FAILED = 'TABLE_DETAILS_FAILED'

export const TABLE_UPDATE_REQUEST = 'TABLE_UPDATE_REQUEST'
export const TABLE_UPDATE_SUCCESS = 'TABLE_UPDATE_SUCCESS'
export const TABLE_UPDATE_FAILED = 'TABLE_UPDATE_FAILED'
export const TABLE_UPDATE_RESET = 'TABLE_UPDATE_RESET'

export const TABLE_DELETE_REQUEST = 'TABLE_DELETE_REQUEST'
export const TABLE_DELETE_SUCCESS = 'TABLE_DELETE_SUCCESS'
export const TABLE_DELETE_FAILED = 'TABLE_DELETE_FAILED'
